# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

import pandas as pd
from sklearn.linear_model import LogisticRegression

# the data set is available at the url below.
URL = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-BD0231EN-SkillsNetwork/datasets/iris.csv"

# using the read_csv function in the pandas library, we load the data into a dataframe.

df = pd.read_csv(URL)

# show 5 random rows from the dataset
df.sample(5)

df.shape

df.Species.value_counts().plot.bar()

# First we identify the target. Target is the value that our machine learning model needs to classify
target = df["Species"]

# We identify the features next. Features are the input values our machine learning model learns from
features = df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]

classifier = LogisticRegression()

classifier.fit(features,target)

#Higher the score, better the model.
classifier.score(features,target)

# Make predictions. Let us predict the species of a flower with SepalLengthCm = 5.4, SepalWidthCm = 2.6, PetalLengthCm = 4.1, PetalWidthCm = 1.3
classifier.predict([[5.4,2.6,4.1,1.3]])