# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

import pandas as pd
from sklearn.linear_model import LogisticRegression


URL2 = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-BD0231EN-SkillsNetwork/datasets/cancer.csv"

df2 = pd.read_csv(URL2)

target = df2["diagnosis"]
features = df2[['radius_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'symmetry_mean']]

classifier2 = LogisticRegression()
classifier2.fit(features,target)

classifier2.score(features,target)

# 'radius_mean' = 13.45, 'perimeter_mean'= 86.6, 'area_mean' = 555.1, 'smoothness_mean' = 0.1022, 'compactness_mean' = 0.08165, 'concavity_mean' = 0.03974, 'symmetry_mean' = 0.1638
result = classifier2.predict([[13.45,86.6,555.1,0.1022,0.08165,0.03974,0.1638]])
print(result)