# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt


# the data set is available at the url below.
URL = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-BD0231EN-SkillsNetwork/datasets/customers.csv"

# using the read_csv function in the pandas library, we load the data into a dataframe.

df = pd.read_csv(URL)

# show 5 random rows from the dataset
df.sample(5)
"""
Fresh_Food	Milk	Grocery	Frozen_Food
103	56082	3504	8906	18028
317	1182	3088	6114	978
342	255	5758	5923	349
24	22647	9776	13792	2915
324	25977	3587	2464	2369
"""
df.shape

df.hist()

number_of_clusters = 3

cluster = KMeans(n_clusters = number_of_clusters)

# Train the model on the dataset
result = cluster.fit_transform(df)

# Your model is now trained. Print cluster centers
cluster.cluster_centers_

# Make the predictions and save them into the column "cluster_number"
df['cluster_number'] = cluster.predict(df)

df.sample(5)

"""
Fresh_Food	Milk	Grocery	Frozen_Food	cluster_number
231	2344	10678	3828	1439	0
346	2771	6939	15541	2693	0
372	3884	3801	1641	876	0
26	9898	961	2861	3151	0
239	47493	2567	3779	5243	1
"""

# Print the cluster numbers and the number of customers in each cluster
df.cluster_number.value_counts()