# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

import pandas as pd
from sklearn.linear_model import LogisticRegression

#import functions for train test split

from sklearn.model_selection import train_test_split


# functions for metrics

from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

# the data set is available at the url below.
URL = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-BD0231EN-SkillsNetwork/datasets/diabetes.csv"

# using the read_csv function in the pandas library, we load the data into a dataframe.

df = pd.read_csv(URL)

# show 5 random rows from the dataset
df.sample(5)
"""
Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age	Outcome
172	2	87	0	23	0	28.9	0.773	25	0
114	7	160	54	32	175	30.5	0.588	39	1
304	3	150	76	0	0	21.0	0.207	37	0
581	6	109	60	27	0	25.0	0.206	27	0
451	2	134	70	0	0	28.9	0.542	23	1
"""
df.shape

df.Outcome.value_counts()

df.Outcome.value_counts().plot.bar()

y = df["Outcome"]

X = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)

classifier = LogisticRegression()

classifier.fit(X_train,y_train)

#Higher the score, better the model.
classifier.score(X_test,y_test)

original_values = y_test
predicted_values = classifier.predict(X_test)


precision_score(original_values, predicted_values) # Higher the value the better the model

recall_score(original_values, predicted_values) # Higher the value the better the model

f1_score(original_values, predicted_values) # Higher the value the better the model

confusion_matrix(original_values, predicted_values) # can be used to manually calculate various met