"""
!pip install pyspark==3.1.2 -q
!pip install findspark -q
"""

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

# FindSpark simplifies the process of using Apache Spark with Python

import findspark
findspark.init()

#import functions/Classes for sparkml

from pyspark.sql import SparkSession

#Create SparkSession
#Ignore any warnings by SparkSession command

spark = SparkSession.builder.appName("SparkSQL").getOrCreate()

# !wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-BD0231EN-SkillsNetwork/datasets/mpg.csv

# Load mpg dataset
mpg_data = spark.read.csv("mpg.csv", header=True, inferSchema=True)

mpg_data.createOrReplaceTempView("mileage")

results = spark.sql("SELECT * FROM mileage WHERE MPG > 40")

# show the results
results.show()

"""
+----+---------+-----------+----------+------+----------+----+--------+
| MPG|Cylinders|Engine Disp|Horsepower|Weight|Accelerate|Year|  Origin|
+----+---------+-----------+----------+------+----------+----+--------+
|43.1|        4|       90.0|        48|  1985|      21.5|  78|European|
|43.4|        4|       90.0|        48|  2335|      23.7|  80|European|
|41.5|        4|       98.0|        76|  2144|      14.7|  80|European|
|44.3|        4|       90.0|        48|  2085|      21.7|  80|European|
|40.8|        4|       85.0|        65|  2110|      19.2|  80|Japanese|
|44.6|        4|       91.0|        67|  1850|      13.8|  80|Japanese|
|46.6|        4|       86.0|        65|  2110|      17.9|  80|Japanese|
|44.0|        4|       97.0|        52|  2130|      24.6|  82|European|
+----+---------+-----------+----------+------+----------+----+--------+
"""

spark.sql("SELECT distinct Origin FROM mileage").show()
"""
+--------+
|  Origin|
+--------+
|European|
|Japanese|
|American|
+--------+
"""

spark.sql("SELECT count(*) FROM mileage where Origin ='Japanese' ").show()
"""
+--------+
|count(1)|
+--------+
|      79|
+--------+
"""

spark.sql("SELECT count(*) FROM mileage where MPG > 40").show()
"""
+--------+
|count(1)|
+--------+
|       8|
+--------+
"""

spark.sql("SELECT Year, count(Year) FROM mileage group by Year").show()
"""
+----+-----------+
|Year|count(Year)|
+----+-----------+
|  78|         36|
|  81|         28|
|  76|         34|
|  72|         28|
|  77|         28|
|  82|         30|
|  80|         27|
|  73|         40|
|  70|         29|
|  75|         30|
|  71|         27|
|  79|         29|
|  74|         26|
+----+-----------+
"""

spark.sql("SELECT max(MPG) FROM mileage").show()
"""
+--------+
|max(MPG)|
+--------+
|    46.6|
+--------+
"""

spark.stop()