# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

# FindSpark simplifies the process of using Apache Spark with Python

import findspark
findspark.init()

from pyspark.sql import SparkSession
from pyspark.ml import Pipeline
from pyspark.ml.pipeline import PipelineModel
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import LinearRegression
from pyspark.ml.feature import StringIndexer
from pyspark.ml.feature import StandardScaler

spark = SparkSession.builder.appName("Practice Project").getOrCreate()

# !wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMSkillsNetwork-BD0231EN-Coursera/datasets/mpg-raw.csv

# Load the dataset
df = spark.read.csv("mpg-raw.csv", header=True, inferSchema=True)

df.show(5)

df.groupBy('Origin').count().orderBy('count').show()

#TODO
rowcount1 = df.count()
print(rowcount1)

df = df.dropDuplicates()

# print the total nunmbr of rows in the dataset
#TODO
rowcount2 = df.count()
print(rowcount2)

# Drop all the rows that contain null values from the dataset
df=df.dropna()

#TODO
rowcount3 = df.count()
print(rowcount3)

df = df.withColumnRenamed("Engine Disp","Engine_Disp")

df.write.mode("overwrite").parquet("mpg-cleaned.parquet")

print("Part 1 - Evaluation")

print("Total rows = ", rowcount1)
print("Total rows after dropping duplicate rows = ", rowcount2)
print("Total rows after dropping duplicate rows and rows with null values = ", rowcount3)
print("Renamed column name = ", df.columns[2])

import os

print("mpg-cleaned.parquet exists :", os.path.isdir("mpg-cleaned.parquet"))

# ML Pipeline creation

df = spark.read.parquet("mpg-cleaned.parquet")
rowcount4 = df.count()

df.show(5)

df.printSchema()

# Stage - 1 Using StringIndexer convert the string column "Origin" into "OriginIndex"
indexer = StringIndexer(inputCol="Origin", outputCol="OriginIndex")

# Stage 2 - assemble the input columns 'Cylinders','Engine_Disp','Horsepower','Weight','Accelerate','Year' into a single column "features"
assembler = VectorAssembler(inputCols=['Cylinders','Engine_Disp','Horsepower','Weight','Accelerate','Year'], outputCol="features")

# Stage 3 - scale the "features" using standard scaler and store in "scaledFeatures" column
scaler = StandardScaler(inputCol="features", outputCol="scaledFeatures")

# Stage 4 - Create a LinearRegression stage to predict "MPG"

lr = LinearRegression(featuresCol="scaledFeatures", labelCol="MPG")

# Build a pipeline using the above four stages

pipeline = Pipeline(stages=[indexer,assembler, scaler, lr])

# Split the data into training and testing sets with 70:30 split. Use 42 as seed
(trainingData, testingData) = df.randomSplit([0.7, 0.3], seed=42)

# Fit the pipeline using the training data

pipelineModel = pipeline.fit(trainingData)

print("Part 2 - Evaluation")
print("Total rows = ", rowcount4)
ps = [str(x).split("_")[0] for x in pipeline.getStages()]

print("Pipeline Stage 1 = ", ps[0])
print("Pipeline Stage 2 = ", ps[1])
print("Pipeline Stage 3 = ", ps[2])

print("Label column = ", lr.getLabelCol())


# Make predictions on testing data
predictions = pipelineModel.transform(testingData)

# Print the MSE 
from pyspark.ml.evaluation import RegressionEvaluator

evaluator = RegressionEvaluator(predictionCol="prediction", labelCol="MPG", metricName="mse")
mse = evaluator.evaluate(predictions)
print(mse)

# Print the MAE
evaluator = RegressionEvaluator(predictionCol="prediction", labelCol="MPG", metricName="mae")
mae = evaluator.evaluate(predictions)
print(mae)


# Print the R2
evaluator = RegressionEvaluator(predictionCol="prediction", labelCol="MPG", metricName="r2")
r2 = evaluator.evaluate(predictions)
print(r2)

print("Part 3 - Evaluation")

print("Mean Squared Error = ", round(mse,2))
print("Mean Absolute Error = ", round(mae,2))
print("R Squared = ", round(r2,2))

lrModel = pipelineModel.stages[-1]

print("Intercept = ", round(lrModel.intercept,2))

# Save the pipeline model
pipelineModel.write().save("Practice_Project")

# Load the pipeline model
loadedPipelineModel = PipelineModel.load("Practice_Project")

# Use the loaded pipeline model for predictions
predictions = loadedPipelineModel.transform(testingData)

# Show the predicted values along with the actual values for the "MPG" column
predictions.select("MPG","prediction").show()

print("Part 4 - Evaluation")

loadedmodel = loadedPipelineModel.stages[-1]
totalstages = len(loadedPipelineModel.stages)
inputcolumns = loadedPipelineModel.stages[1].getInputCols()

print("Number of stages in the pipeline = ", totalstages)
for i,j in zip(inputcolumns, loadedmodel.coefficients):
    print(f"Coefficient for {i} is {round(j,4)}")

spark.stop()